### ISSUE TITLE
Binary releases?

### ISSUE THREAD

**Issue by IlDucci** [sewer56lol/dlang-prs#1]
Good evening. I was looking for a PRS decompressor/recompressor and I stumbled on your project. I don't have too much of an idea of compiling code, but a friend told me your code is a library rather than a tool. I'm tinkering around with a DC/PS2 game that has PRS compression and I would like to ask if you could turn this into a working tool for less programming-savvy people.

Thank you.

**Comment by Sewer56** [comment]
Sorry for taking my time to reply.

The day it was posted I left to go abroad for a family visit where I don't get to spend too much time on my laptop and thought I'd get to this when I get back home (2 days from now); but then I did kind of feel bad about leaving this post hanging for too long.

I'll have a simple GUI available soon-ish; maybe around 4 days as I quite plainly am not a fan of working on anything GUI related with a touchpad.

-----------------

On another note; since the readme doesn't but probably should mention it.
The C# wrapper for this library is available on [NuGet](https://www.nuget.org/packages/csharp-prs/)

**Comment by IlDucci** [comment]
Thank you!

**Comment by Sewer56** [comment]
There should be a simple drag-drop GUI for files in the Releases section now.
I didn't make it very complex, settled for simplicity this time around and wrote it in under two hours; it should be easy to use.

![](https://i.imgur.com/gFsEvNl.png)

**Comment by IlDucci** [comment]
Thank you very much!

I just did some tests with a RDT file from Code Veronica (PS2 PAL version). Wow, that was fast! Even at the maximum range (Which has the closest filesize to the original) it's just a matter of seconds, instead of the approximate minute it took with other tools! The files work on a real PS2, so great job!

While the GUI could have more features, I leave the closure of this ticket up to you.

**Comment by IlDucci** [comment]
Howdy!

I just passed over this repo and saw your updates. I asked a fried to try to compile it, but it seems he's been having issues trying to get D working in his environment (couldn't find link.exe, I think). Could you please update the releases again?

Thank you for your time and Merry Christmas.

**Comment by Sewer56** [comment]
> Howdy!
> 
> I just passed over this repo and saw your updates. I asked a fried to try to compile it, but it seems he's been having issues trying to get D working in his environment (couldn't find link.exe, I think). Could you please update the releases again?
> 
> Thank you for your time and Merry Christmas.

Yeah no problem. Some of the tooling around D is still early and there are sometimes some more drastic changes here and there from time to time.

Although I think the language is fantastic, I sadly don't get to work with it very often so it'll be like doing it from scratch for me too. There's a reason I have some primitive build instructions.

I'm currently napping, gimme 4-6 hours and I'll be up for doing this.

I'll post if I find anything unusual ;).

Edit: Til I wake up, just a small reminder for your friend. The GUI is a .NET project, and this package has a .NET wrapper which is up to date. You can just switch it out from a project reference to NuGet.,

**Comment by Sewer56** [comment]
Holy crap there's a bug in the optimizations I added recently. This is not good. Might take a bit more time :P

**Comment by Sewer56** [comment]
Ok all done. Have a Merry Christmas @IlDucci

**Comment by IlDucci** [comment]
Thank you!
